### ISSUE TITLE
bots code reverts to original on save

### ISSUE THREAD

**Issue by greggthebax** [ues-io/uesio#4061]
When editing Bots dialogue and selecting save reverts the edited code.

Only happens after the first edit and save.

**Comment by abeljimo** [comment]
To solve this one I want to talk to @humandad first; I noticed the problem and will try to explain it so it can be fixed quickly.
The component is requesting the old file because changing the attachment is not a change in the bot itself.

https://studio.uesio-dev.com:3000/site/userfiles/download?userfileid=0190a1ca-360a-712a-9129-0ad2940ce1f7&version=1720701677
https://studio.uesio-dev.com:3000/site/userfiles/download?userfileid=0190a1ca-360a-712a-9129-0ad2940ce1f7&version=1720701677

if you change the code of the BOT (the attachment) & the label of the bot for example the result is the expected one.
But if you change the code of the BOT (the attachment) we don't notice the change since it's not part of the main item.

@humandad the question is, shall we update the BOT **_uesio/core.updatedat_** when the attachment is changed? 
I am not sure how to take an approach to fix it but we can discuss some options at some point. 
But 100% sure that Is the issue.

I hope is clear!

**Comment by humandad** [comment]
This should be fixed now.
